version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
createbigcannons = true
cccbridge = true
create_vibrant_vaults = true
vista = true
extra_gauges = true
customnpcs = true
createpropulsion = true
copperagebackport = true
create = true
createrailwaysnavigator = true
aeronautics = true
createcasing = true
numismatics = true
simulated = true
advancedperipherals = true
copycats = true
minecraft = true
dndecor = true
spring_to_life = true
railways = true
bellsandwhistles = true
createframed = true
dragonlib = true
moonlight = true
computercraft = true
vanillabackport = true
pipeorgans = true
exposure = true
create_power_loader = true
