# Use Cloth Config mod for the descriptions.
---
snowGravity: true
snowMakingIce: true
snowAlwaysReplaceable: true
thinnerBoundingBox: false
snowNeverMelt: false
snowSpawnMaxLightLevel: 9
snowPersistMaxLightLevel: 11
snowReduceFallDamage: true
sustainGrassIfLayerMoreThanOne: true
sneakSnowball: false
fancySnowOnUpperSlab: true
rightClickToggleFancySnow: true
mobSpawningMaxLayers: 8
snow-cover:
  restoreOriginalBlocks: false
  replaceWorldgenFeature: true
  placeSnowOnBlock: true
  placeNaturally: true
accumulation:
  naturalMelting: false
  smoothAccumulation: true
  snowAndIceMeltInWarmBiomes: false
  maxLayers: 4
  accumulatesDuringSnowstorm: false
  accumulatesDuringSnowfall: false
integration:
  accumulationWinterOnly: false
debug:
  forceVanillaIceSnowLogic: false
  mobSpawningCommand: false
