name = "Modulo Create"
author = "alexxunderscore"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1f50bca68deb4c75f28da41a274509c6f26c6b091cb12483f563eae84f2c5d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
unsup = "1.2.7"
