name = "Modulo Create"
author = "alexxunderscore"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eca16836543b7e1107eb5a4da4bd33a138768ba15ff9c784c9a391473e2dafd1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
unsup = "1.2.7"
