name = "Modulo Create"
author = "alexxunderscore"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5537819836296ee38638572b7f254cd17e8f82a5da2ade8c8e78993fcd17289c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
unsup = "1.2.7"
