[flavor_groups.shaders]
name = "Install Shaders"
description = "WARNING: Shader mods may decrease performance even when shaders are DISABLED!\nSome mods do not support shaders well, and performance will be heavily impacted!\nIf you still want shaders, set to Install! Only Complementary Reimagined will be supported.\n"
side = "client"

[[flavor_groups.shaders.choices]]
id = "no_shaders"
name = "Skip"
description = "Do not install Shaders."
[[flavor_groups.shaders.choices]]
id = "shaders"
name = "Install"
description = "Install Iris, Euphoria Patches, Colorwheel, Create Better FPS, and Complimentary Reimagined."

[flavor_groups.admin]
name = "Admin Mods"
description = "Recommended to SKIP!\nMods I use for profiling and configuring\n"
side = "both"
[[flavor_groups.admin.choices]]
id = "no_admin_mods"
name = "[Recommended] Skip"
description = "Do not install Admin mods."
[[flavor_groups.admin.choices]]
id = "admin"
name = "Install"
description = "Install Admin mods."

[flavor_groups.server]
name = "[IGNORE] Server Mods Only"
description = "Only for server!"
side = "both"
[[flavor_groups.server.choices]]
id = "modpack"
name = "[REQUIRED] Skip"
description = "Install as normal."
[[flavor_groups.server.choices]]
id = "server"
name = "Server Install"
description = "Install for server ONLY\nSkip client mods"

[metafile.iris]
flavors = "shaders"
[metafile.euphoria-patches]
flavors = "shaders"
[metafile.colorwheel]
flavors = "shaders"
[metafile.createbetterfps]
flavors = "shaders"
[metafile."/shaderpacks/complimentary-reimagined.pw.toml"]
flavors = "shaders"

[metafile.crash-assistant]
flavors = "admin"
[metafile.observable]
flavors = ["admin", "server"]
[metafile.obscuras-panoramica]
flavors = "admin"
[metafile.sdlink]
flavors = ["admin", "server"]
[metafile.reliable-replacer]
flavors = ["admin", "server"]
[metafile.probejs]
flavors = "admin"
[metafile.monkeylib538]
flavors = ["admin", "server"]
[metafile.mesh-lib]
flavors = ["admin", "server"]
[metafile.git-pack-manager]
flavors = ["admin", "server"]
[metafile.adventure-platform-mod]
flavors = ["admin", "server"]

[metafile.controlling]
flavors = "modpack"
[metafile.yeetus-experimentus]
flavors = "modpack"
[metafile.chat-heads]
flavors = "modpack"
[metafile.better-advancements]
flavors = "modpack"
[metafile.emi-plus-backport]
flavors = "modpack"
[metafile.lambdynamiclights]
flavors = "modpack"
[metafile.bigsignwriter]
flavors = "modpack"
[metafile.dynamic-fps]
flavors = "modpack"
[metafile.morebeeinfo]
flavors = "modpack"
[metafile.reeses-sodium-options]
flavors = "modpack"
[metafile.ssrd]
flavors = "modpack"
[metafile.entityculling]
flavors = "modpack"
[metafile.particular-reforged]
flavors = "modpack"
[metafile.emi-enchanting]
flavors = "modpack"
[metafile.simple-discord-rpc]
flavors = "modpack"
[metafile.tmrv]
flavors = "modpack"
[metafile.asyncparticles]
flavors = "modpack"
[metafile.better-clouds]
flavors = "modpack"
[metafile.cubes-without-borders]
flavors = "modpack"
[metafile.ok-zoomer]
flavors = "modpack"
[metafile.entitytexturefeatures]
flavors = "modpack"
[metafile.entity-model-features]
flavors = "modpack"
[metafile.sodium]
flavors = "modpack"
[metafile.extreme_sound_muffler]
flavors = "modpack"
[metafile."mods/i-know-how-to-play!.pw.toml"]
flavors = "modpack"
[metafile.seamless-loading-screen]
flavors = "modpack"
[metafile.immediatelyfast]
flavors = "modpack"
[metafile.create-nowheel]
flavors = "modpack"
[metafile.moreculling]
flavors = "modpack"
[metafile.searchables]
flavors = "modpack"
[metafile.flerovium]
flavors = "modpack"
[metafile.simplefog]
flavors = "modpack"
[metafile.sodium-shadowy-path-blocks]
flavors = "modpack"
[metafile.particle-rain]
flavors = "modpack"
[metafile.no-chat-restrictions]
flavors = "modpack"
[metafile.resourcepackcached]
flavors = "modpack"
[metafile.freecam]
flavors = "modpack"